version = 0.1

[default.deploy.parameters]
stack_name = "weather-forecast-app"
resolve_s3 = true
s3_prefix = "weather-forecast-app"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true

[default.global.parameters]
region = "eu-west-2"
